---
title: "Normative modeling readme"
author: "Richard"
date: "14/01/2018"
output: html_document
---
# Normative modeling in Autism - readme file

## Setup
general setup script to load all packages and install them if the are not already on the system

```{r, include=FALSE}
  install.packages('easypackages')
  rm(list = ls()) # clear the workspace
  library(easypackages) # then we can do the rest in one go
  
  # get a list of useful packages
  list.of.packages <- c("Hmisc","ggplot2","caret","gplots","Rmisc","dplyr",
            "MatchIt","optmatch","data.table","plotrix","ggthemes",
            "viridis","coin","plyr","psytabs","RColorBrewer",
            "msir","lmtest", "ggpubr","stats", "reshape2","xtable",
            "ez","apa","parallel", "jmuOutlier","Rtsne","fpc", "cluster",
            "RCurl")

  # check if they are already installed and otherwise install them (not that
  # this doesn't work for biocLite tools!)
  new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
  if(length(new.packages)>0) { install.packages(new.packages)}

  # then load them all
  libraries(list.of.packages)
  rm(list.of.packages, new.packages)
```

### Set the working directory and load the custom functions 
```{r, include=FALSE}
  # set the working directory
  setwd("~")

  source("./Scripts/variancePart.R")
  source("./Scripts/2_localRegression.R")
  source("./Scripts/3_Stats.R")
  source("./Scripts/4_SymptomCorrelations.R")
```

## Data merging


## Data inspection
```{r, include=FALSE}
varianceStats(measure = "CT", parcellation = "500aparc")

```

## Local regression and obtaining normative scores
```{r, include=FALSE}
Job1 = mcparallel(localRegression(measure = "CT", parcellation = "HCP"))
Job2 = mcparallel(localRegression(measure = "CT", parcellation = "500aparc"))
mccollect(list(Job1, Job2))
```

## Run stats
```{r, include=FALSE}
Job1 = mcparallel(basicStats(measure = "CT", parcellation = "500aparc"))
Job2 = mcparallel(basicStats(measure = "CT", parcellation = "HCP"))
mccollect(list(Job1, Job2))
```

## Symptom*W-Score correlation
```{r, include=FALSE}
Job1 = mcparallel(symptomCorrelation(measure = "CT", parcellation = "HCP"))
Job2 = mcparallel(symptomCorrelation(measure = "CT", parcellation = "500aparc"))
mccollect(list(Job1, Job2))
```